dist: trusty
language: java
jdk:
- oraclejdk14
deploy:
  provider: heroku
  api_key:
    secure: $SECURE_KEY
  app: $APP
  on:
    repo: AquillaSLeite/beer_api_digital_innovation_one
    branch: main
  skip_cleanup: 'true'
notifications:
  email: false
